Dev
David-Damato/Mood_Mixtape pull request #26
Opened 2021-04-28 07:38 UTC by David-Damato

2021-04-29 08:46 UTC, alinedubois approved these changes

2021-04-30 11:37 UTC, KatalinaNadasi requested changes
Bravo pour votre travail déjà très complet !
Des erreurs récurantes toujours au même endroit : 
- Utilisation du franglais : le code est toujours en anglais
- Utilisation de breakpoint de mediaqueries pas en accord à des valeurs précises qui existent
- utilisation des classes pas bien comprises : une classe doit être réutilisées un maximum de fois si propriétés identiques, ici on a recréé des noms de classes avec les même propriétés ce qui fait beaucoup de duplication de code
- Code relativement clean par ailleurs, bravo : travail de refactorisation à prévoir pour utiliser un promise.all pour faire plusieurs promesses dans un seul useEffect.

Bon courage !

2021-04-30 11:37 UTC, KatalinaNadasi commented on src/components/Accueil/AccueilContenu.css
> +    margin-top: 3%;
possible de mettre sur une ligne `margin: 3% 5% 0 5%`=> les valeurs correspondent à top right bottom left

2021-04-30 11:37 UTC, KatalinaNadasi commented on src/components/Accueil/AccueilContenu.css
> +    margin-right: 5%;
pareil : `margin 0 5%` quand il n'y a que deux valeurs c'est val1 : top et bottom, val2: right et left

2021-04-30 11:37 UTC, KatalinaNadasi commented on src/components/Accueil/AccueilContenu.css
> +    .questionsEncadre {
plutôt en anglais :)

2021-04-30 11:37 UTC, KatalinaNadasi commented on src/components/Accueil/AccueilContenu.css
> +    .reponse-appears {
pareil : en anglais

2021-04-30 11:37 UTC, KatalinaNadasi commented on src/components/Accueil/AccueilContenu.css
> +
Puisqu'il n'y a que la font-size qui se rajoute entre reponse-appears et .reponse-hidden plutôt faire une classe .answer et une props en React 'hidden' : quand il y a la props hidden on rajoute une classe avec la font-size ?

2021-04-30 11:37 UTC, KatalinaNadasi commented on src/components/Accueil/AccueilContenu.css
> +        width: 300px;
plutôt des width en % pour éviter de réajuster en responsive avec une nouvelle valeur.

2021-04-30 11:37 UTC, KatalinaNadasi commented on src/components/Accueil/AccueilContenu.css
> +        margin-bottom: 200px;
il vaut mieux n'utiliser que des % ou que des px pour les margin mais pas un mélange des 2. D'ailleurs pour margin et padding on va plutôt utiliser rem comme valeur relative ;)

2021-04-30 11:37 UTC, KatalinaNadasi commented on src/components/Accueil/AccueilContenu.css
> +    .question {
English please 🙏

2021-04-30 11:37 UTC, KatalinaNadasi commented on src/components/Accueil/AccueilContenu.css
> +        width: 350px;
Plutôt en %

2021-04-30 11:37 UTC, KatalinaNadasi commented on src/components/Accueil/AccueilContenu.css
> +
IL y a exactement les mêmes valeurs dans .question et  .reponse-appears : il faut n'utiliser qu'une seule et unique classe qui sera appelée quand on en a besoin : ne jamais rajouter de classe s'il y a les mêmes propriétés que dans une autre classe.

2021-04-30 11:37 UTC, KatalinaNadasi commented on src/components/Accueil/AccueilContenu.css
> +
Pareil ici : ne prendre qu'une seule classe pour ne pas répéter le code qui est le même dans les 2 classes

2021-04-30 11:37 UTC, KatalinaNadasi commented on src/components/App/app.js
On n'utilise plus de classes en React (ça c'était avant) : on utilise des composant fonctionnels et des hooks :)

2021-04-30 11:37 UTC, KatalinaNadasi commented on src/components/App/menu/Menu.js
> -                                texte={"Playlist"}
text in english

2021-04-30 11:37 UTC, KatalinaNadasi commented on src/components/App/menu/Menu.js
>                                  icone={"music"}
icon 🏴

2021-04-30 11:37 UTC, KatalinaNadasi commented on src/components/Footer/footer.css
> +
Attention à bien utiliser des endpoints qui existent https://media-queries.aliasdmc.fr/media-queries-live.php

2021-04-30 11:37 UTC, KatalinaNadasi commented on src/components/Mood/MoodInLove.js
> +import MoodEnTete from "./MoodEnTete";
English 🏴󠁧󠁢󠁥󠁮󠁧󠁿

2021-04-30 11:37 UTC, KatalinaNadasi commented on src/components/Playlist/DetailPlaylist.js
> +    const [chanson, setChanson] = useState(null);
English 🏴󠁧󠁢󠁥󠁮󠁧󠁿

2021-04-30 11:37 UTC, KatalinaNadasi commented on src/components/Playlist/DetailPlaylist.js
> +        <div className={`conteneur-horizontal ${className} playlist-detail playlist-${type.toLowerCase()}`}>
English 🏴󠁧󠁢󠁥󠁮󠁧󠁿

2021-04-30 11:37 UTC, KatalinaNadasi commented on src/components/Playlist/OngletMood.js
> +export const OngletMood = ({type, playlistSelectionnee, setPlaylistSelectionnee}) => {
english 🏴󠁧󠁢󠁥󠁮󠁧󠁿

2021-04-30 11:37 UTC, KatalinaNadasi commented on src/components/Playlist/Player.css
> +
Se sont les mêmes valeurs donc prévoir un seul breakpoint directement : @media screen and (min-width: 560px) and (max-width: 1440px)

2021-04-30 11:37 UTC, KatalinaNadasi commented on src/components/Playlist/playlist.css
> +@media screen and (max-width: 800px){
Pareil : un seul breakpoint avec la même valeur pour éviter de répéter le code

2021-04-30 11:37 UTC, KatalinaNadasi commented on src/components/Playlist/playlist.js
We use the useEffect just once in a component, to make multiple promises you need to use Promise.all https://www.andreasreiterer.at/single-result-with-promise-all/

2021-04-30 11:37 UTC, KatalinaNadasi commented on src/components/Playlist/playlist.js
> +                    <OngletMood
good moove 👏

2021-05-03 12:37 UTC, vio9 commented on src/components/Accueil/AccueilContenu.css
> +    margin-top: 3%;
done

2021-05-03 12:41 UTC, vio9 commented on src/components/Accueil/AccueilContenu.css
> +    margin-right: 5%;
done

2021-05-03 13:02 UTC, vio9 commented on src/components/Accueil/AccueilContenu.css
> +    .questionsEncadre {
done

2021-05-03 13:10 UTC, vio9 commented on src/components/Accueil/AccueilContenu.css
> +    .reponse-appears {
done

2021-05-03 13:33 UTC, vio9 commented on src/components/Accueil/AccueilContenu.css
> +
done

2021-05-03 13:49 UTC, vio9 commented on src/components/Accueil/AccueilContenu.css
> +        width: 300px;
300% changé en 40%

2021-05-03 13:58 UTC, vio9 commented on src/components/Accueil/AccueilContenu.css
> +        margin-bottom: 200px;
ok. 200px transformé en 25%

2021-05-03 13:59 UTC, vio9 commented on src/components/Accueil/AccueilContenu.css
> +    .question {
ok

2021-05-03 14:01 UTC, vio9 commented on src/components/Accueil/AccueilContenu.css
> +        width: 350px;
remplacé par 50%

2021-05-03 14:06 UTC, vio9 commented on src/components/Accueil/AccueilContenu.css
> +
les classes n'ont en fait pas les mêmes propriétés de margin-left. donc deux classes necessaires ici  (question 5% et reply 45%)

2021-05-03 14:12 UTC, vio9 commented on src/components/Accueil/AccueilContenu.css
> +
ok transformé en .questionReply et ajouté en plus dans Accueil questions.js

2021-05-03 14:24 UTC, vio9 commented on src/components/App/app.js
transformé en compnent fonctionnel.

2021-05-03 14:33 UTC, vio9 commented on src/components/App/menu/Menu.js
> -                                texte={"Playlist"}
done

2021-05-03 14:33 UTC, vio9 commented on src/components/App/menu/Menu.js
>                                  icone={"music"}
done

2021-05-03 14:38 UTC, vio9 commented on src/components/Footer/footer.css
> +
corrigé

2021-05-03 14:50 UTC, vio9 commented on src/components/Mood/MoodInLove.js
> +import MoodEnTete from "./MoodEnTete";
done

2021-05-03 14:58 UTC, vio9 commented on src/components/Playlist/DetailPlaylist.js
> +    const [chanson, setChanson] = useState(null);
ok done

2021-05-03 14:58 UTC, vio9 commented on src/components/Playlist/DetailPlaylist.js
> +        <div className={`conteneur-horizontal ${className} playlist-detail playlist-${type.toLowerCase()}`}>
done

2021-05-03 15:05 UTC, vio9 commented on src/components/Playlist/OngletMood.js
> +export const OngletMood = ({type, playlistSelectionnee, setPlaylistSelectionnee}) => {
done

2021-05-03 15:09 UTC, vio9 commented on src/components/Playlist/Player.css
> +
done

2021-05-03 15:11 UTC, vio9 commented on src/components/Playlist/playlist.css
> +@media screen and (max-width: 800px){
done

2021-05-05 12:41 UTC, merged